import { NextResponse } from "next/server";

export async function GET() {
  const images = {
    1: "/assets/img/kanin.jpg",
    2: "/assets/img/menu/Ham.webp",
    3: "/assets/img/egg.jpg",
    4: "/assets/img/Macaroni.jpg",
    5: "/assets/img/menu/sopas.png",
    6: "/assets/img/buttermilk.jpg",
    7: "/assets/img/porkchop.jpg",
    8: "/assets/img/Pork Caldereta.jpg",
    9: "/assets/img/menu/chicken adobo.jpg",
    10: "/assets/img/chopsuey.jpg",
    11: "/assets/img/hakdog.jpg",
    12: "/assets/img/menudo.jpg",
    13: "/assets/img/menu/curry.jpg",
    14: "/assets/img/pakbet.jpg",
    15: "/assets/img/menu/pork tapa.jpg",
    16: "/assets/img/menu/chicken afritada.jpg",
    17: "/assets/img/menu/sayote gisado.jpg",
    18: "/assets/img/menu/longganisa.jpg",
    19: "/assets/img/menu/shanghai.webp",
    20: "/assets/img/menu/spaghetti.jpg",
    21: "/assets/img/menu/Pork pansit canton.jpg",
    22: "/assets/img/menu/lomi.jpg",
    23: "/assets/img/menu/pork sinigang.jpg",
    24: "/assets/img/menu/pininyahang manok.jpg",
    25: "/assets/img/menu/ginataang langka.jpg",
    26: "/assets/img/menu/champorado.webp",
    27: "/assets/img/menu/inihaw na liempo.jpg",
    28: "/assets/img/menu/monggo.webp",
    29: "/assets/img/menu/burger steak.jpg",
    30: "/assets/img/menu/laing.jpg",
    31: "/assets/img/menu/skinless.jpg",
    32: "/assets/img/bihon.jpg",
    33: "/assets/img/menu/igado.jpg  ",
    34: "/assets/img/menu/bopis.jpg",
    35: "/assets/img/menu/pork brocolli.jpg",
    36: "/assets/img/dinuguan.jpg",
    37: "/assets/img/menu/sweet and sour.jpg",
    38: "/assets/img/menu/patolang miswa.jpg",
    39: "/assets/img/menu/lechon paksiw.jpg",
    40: "/assets/img/menu/ginataang kalabasa.jpg",
    41: "/assets/img/gigantic_water.jpg",
    42: "/assets/img/conk.jpg",
    43: "/assets/img/spront.jpg",
    44: "/assets/img/menu/zesto.jpg",
    45: "/assets/img/menu/yakult.webp",
    46: "/assets/img/menu/tocino.webp",
    47: "/assets/img/menu/bicol.jpg",
    48: "/assets/img/menu/humba.jpg",
    49: "/assets/img/menu/giniling.webp",
    50: "/assets/img/menu/ampalaya.webp",
    51: "/assets/img/menu/fried_rice.jpg",
    52: "/assets/img/menu/neck.jpg",
    53: "/assets/img/menu/minute.webp",
    54: "/assets/img/menu/palabok_hihi.jpg",
    55: "/assets/img/menu/fillet.jpg",
    56: "/assets/img/menu/pork-steak.jpg",
    57: "/assets/img/menu/PORK-MENUDO.webp",
    58: "/assets/img/menu/PORK-MENUDO.webp",
    59: "/assets/img/menu/royal.jpg",
    60: "/assets/img/menu/Penne.webp",
    61: "/assets/img/menu/royal.jpg",
    62: "/assets/img/menu/royal.jpg",
    63: "/assets/img/menu/Estofado.webp",
    64: "/assets/img/menu/royal.jpg",
    65: "/assets/img/menu/royal.jpg",
    66: "/assets/img/menu/royal.jpg",
    67: "/assets/img/menu/royal.jpg",
    68: "/assets/img/menu/Bella.jpg",
    69: "/assets/img/menu/royal.jpg",
    70: "/assets/img/menu/royal.jpg",
    71: "/assets/img/menu/royal.jpg",
    72: "/assets/img/menu/maja.jpg",
  };

  return NextResponse.json(images);
}
