import { NextResponse } from "next/server";

export async function GET() {
  const images = {
    1: "/assets/img/kanin.jpg",
    2: "/assets/img/menu/Ham.webp",
    3: "/assets/img/egg.jpg",
    4: "/assets/img/Macaroni.jpg",
    5: "/assets/img/sopas.png",
    6: "/assets/img/pork_buttermilk.jpg",
    7: "/assets/img/menu/porkchop.jpg",
    8: "/assets/img/Pork Caldereta.jpg",
    9: "/assets/img/chicken adobo.jpg",
    10: "/assets/img/chopsuey.jpg",
    11: "/assets/img/smol_hotdog.webp",
    12: "/assets/img/menudo.jpg",
    13: "/assets/img/curry.jpg",
    14: "/assets/img/pakbet.jpg",
    15: "/assets/img/menu/pork tapa.jpg",
    16: "/assets/img/menu/chicken afritada.jpg",
    17: "/assets/img/menu/sayote gisado.jpg",
    18: "/assets/img/menu/longganisa.jpg",
    19: "/assets/img/menu/shanghai.webp",
    20: "/assets/img/menu/spaghetti.jpg",
    21: "/assets/img/menu/Pork pansit canton.jpg",
    22: "/assets/img/menu/lomi.jpg",
    23: "/assets/img/menu/pork sinigang.jpg",
    24: "/assets/img/menu/pininyahang manok.jpg",
    25: "/assets/img/menu/ginataang langka.jpg",
    26: "/assets/img/menu/champorado.webp",
    27: "/assets/img/menu/inihaw na liempo.jpg",
    28: "/assets/img/menu/monggo.webp",
    29: "/assets/img/menu/burger steak.jpg",
    30: "/assets/img/menu/laing.jpg",
    31: "/assets/img/menu/skinless.jpg",
    32: "/assets/img/menu/bihon.jpg",
    33: "/assets/img/menu/igado.jpg  ",
    34: "/assets/img/menu/bopis.jpg",
    35: "/assets/img/menu/pork brocolli.jpg",
    36: "/assets/img/menu/dinuguan.jpg",
    37: "/assets/img/menu/sweet and sour.jpg",
    38: "/assets/img/menu/patolang miswa.jpg",
    39: "/assets/img/menu/lechon paksiw.jpg", 
    40: "/assets/img/menu/ginataang kalabasa.jpg",
    41: "/assets/img/menu/gigantic_water.jpg", 
    42: "/assets/img/menu/conk.jpg",
    43: "/assets/img/menu/spront.jpg",
    44: "/assets/img/menu/zesto.jpg",
    45: "/assets/img/menu/yakult.jpg",
    46: "/assets/img/menu/tocino.webp",
  };

  return NextResponse.json(images);
}
