import { NextResponse } from "next/server";

export async function GET() {
  const images = {
    1: "/assets/img/kanin.jpg",
    2: "/assets/img/menu/Ham.webp",
    3: "/assets/img/egg.jpg",
    4: "/assets/img/menu/Macaroni.jpg",
    5: "/assets/img/menu/sopas.png",
    6: "/assets/img/menu/buttermilk.jpg",
    7: "/assets/img/menu/Pork Caldereta.jpg",
    8: "/assets/img/menu/chicken adobo.jpg",
    
    9: "/assets/img/menu/chopsuey.jpg",
    10: "/assets/img/hakdog.jpg",
    11: "/assets/img/menu/menudo.jpg",
    12: "/assets/img/menu/curry.jpg",
    13: "/assets/img/pakbet.jpg",
    14: "/assets/img/menu/pork tapa.jpg",
    15: "/assets/img/menu/chicken afritada.jpg",
    16: "/assets/img/menu/sayote gisado.jpg",
    17: "/assets/img/menu/longganisa.jpg",
    18: "/assets/img/menu/shanghai.webp",
    19: "/assets/img/menu/spaghetti.jpg",
    20: "/assets/img/menu/pansit canton.jpg",
    21: "/assets/img/menu/lomi.webp",
    

    22: "/assets/img/menu/pininyahang manok.jpg",
    23: "/assets/img/menu/ginataang langka.jpg",
    24: "/assets/img/menu/champorado.webp",
    25: "/assets/img/menu/inihaw na liempo.jpg",
    26: "/assets/img/menu/monggo.webp",
    27: "/assets/img/menu/burger steak.jpg",
    28: "/assets/img/menu/laing.jpg",
    29: "/assets/img/menu/skinless.jpg",
    30: "/assets/img/bihon.jpg",
    31: "/assets/img/menu/igado.jpg  ",
    32: "/assets/img/menu/bopis.jpg",
    33: "/assets/img/menu/pork brocolli.jpg",
    34: "/assets/img/dinuguan.jpg",
    35: "/assets/img/menu/sweet and sour.jpg",
    36: "/assets/img/menu/patolang miswa.jpg",
    37: "/assets/img/menu/lechon paksiw.jpg",
    38: "/assets/img/menu/ginataang kalabasa.jpg",
    39: "/assets/img/menu/SPRING.png",
    40: "/assets/img/conk.jpg",
    41: "/assets/img/spront.jpg",
    42: "/assets/img/menu/SESTO.jpg",
    43: "/assets/img/menu/yakult.webp",
    44: "/assets/img/menu/tocino.webp",
    45: "/assets/img/menu/bicol.jpg",
    46: "/assets/img/menu/humba.jpg",
    47: "/assets/img/menu/giniling.webp",
    48: "/assets/img/menu/ampalaya.webp",
    49: "/assets/img/menu/RICE_PRITO.jpg",
    50: "/assets/img/menu/neck.jpg",
    51: "/assets/img/menu/minute.webp",
    52: "/assets/img/menu/palabok_hihi.jpg",
    53: "/assets/img/menu/fillet.jpg",
    54: "/assets/img/menu/pork-steak.jpg",
    55: "/assets/img/menu/PORK-MENUDO.webp",
    56: "/assets/img/menu/pork sinigang.webp",
    57: "/assets/img/menu/royal.jpg",
    58: "/assets/img/menu/CARBON.jpg",
    59: "/assets/img/menu/MALING.webp",
    60: "/assets/img/menu/CHICKENASADO.jpg",
    61: "/assets/img/menu/Estofado.webp",
    62: "/assets/img/menu/Penne.webp",
    63: "/assets/img/menu/dew.png",
    64: "/assets/img/menu/BEANS.jpg",
    65: "/assets/img/menu/C2.webp",
    66: "/assets/img/menu/BOLOGNA.jpg",
    67: "/assets/img/menu/TALOMNG.jpg",
    68: "/assets/img/porkchop.jpg",
    69: "/assets/img/menu/tokwa.jpg",
    70: "/assets/img/menu/maja.jpg",
  };

  return NextResponse.json(images);
}

